GET http://tevent.herokuapp.com/api/v1
###
GET http://tevent.herokuapp.com/api/v1/health
###




POST http://tevent.herokuapp.com/api/v1/signin
@Content-type: application/json

{ "name": "Paul", "email": "paul@com", "secret": "123" }
###
POST http://tevent.herokuapp.com/api/v1/login
@Content-type: application/json

{ "email": "paul@com", "secret": "234" }
###
GET http://tevent.herokuapp.com/api/v1/user
###
PUT http://tevent.herokuapp.com/api/v1/user
@Content-type: application/json

{ "name": "Pavel", "email": "paul@com" }
###




POST http://tevent.herokuapp.com/api/v1/organizations
@Content-type: application/json

{ "name": "Scala Community" }
###
GET http://tevent.herokuapp.com/api/v1/organizations/1
###
POST http://tevent.herokuapp.com/api/v1/organizations/1/join
@Content-type: application/json

{ "participationType": "sub" }
###




POST http://tevent.herokuapp.com/api/v1/events
@Content-type: application/json

{ "organizationId": 1, "name": "Meetup #1", "datetime": "2021-01-10T10:15:30+03:00", "location": "Moscow", "capacity": 100 }
###
GET http://tevent.herokuapp.com/api/v1/events?organization=1
###
GET http://tevent.herokuapp.com/api/v1/user/organizations
###

POST http://tevent.herokuapp.com/api/v1/events/1/join
@Content-type: application/json

{ "participationType": "offline" }
###
GET http://tevent.herokuapp.com/api/v1/user/events
###
POST http://tevent.herokuapp.com/api/v1/events/1/leave
###
