### SIGN IN
POST http://tevent.herokuapp.com/api/v1/signin
@Content-type: application/json

{ "name": "Turist", "email": "paul@ya.ruuu", "secret": "8765" }

### LOGIN
POST http://tevent.herokuapp.com/api/v1/login
@Content-type: application/json

{ "email": "paul@ya.ruuu", "secret": "1234" }







### USER INFO
GET http://tevent.herokuapp.com/api/v1/user
###

PUT http://tevent.herokuapp.com/api/v1/user
@Content-type: application/json

{ "name": "Pavel", "email": "paul@com" }
###

DELETE http://tevent.herokuapp.com/api/v1/user








### ADD ORGANIZATION
POST http://tevent.herokuapp.com/api/v1/organizations
@Content-type: application/json

{ "name": "Dev Community", "tags": ["dev"] }

### CHANGE
PUT http://tevent.herokuapp.com/api/v1/organizations/1
@Content-type: application/json

{ "name": "Developers Community", "tags": ["dev", "it"] }



### INFO & SEARCH
GET http://tevent.herokuapp.com/api/v1/organizations/1
###
GET http://tevent.herokuapp.com/api/v1/organizations?tags=dev



### SUBSCRIBE TO ORGANIZATION (sub, member, manager, owner)
POST http://tevent.herokuapp.com/api/v1/organizations/1/join
@Content-type: application/json

{ "participationType": "sub" }

### GET USERS
GET http://tevent.herokuapp.com/api/v1/organizations/1/users

### UNSUBSCRIBE
POST http://tevent.herokuapp.com/api/v1/organizations/1/leave






### CREATE EVENT
POST http://tevent.herokuapp.com/api/v1/events
@Content-type: application/json

{ "organizationId": 1, "name": "Meetup #1", "datetime": "2021-01-10T10:15:30+03:00", "location": "Moscow", "capacity": 100 }



### INFO & SEARCH
GET http://tevent.herokuapp.com/api/v1/events/1
###
GET http://tevent.herokuapp.com/api/v1/events?organization=1



### REGISTER TO EVENT (online, offline)
POST http://tevent.herokuapp.com/api/v1/events/1/join
@Content-type: application/json

{ "participationType": "offline" }

### GET USERS
GET http://tevent.herokuapp.com/api/v1/events/1/users
###
POST http://tevent.herokuapp.com/api/v1/events/1/leave





### USER EVENTS & ORGANIZATIONS
GET http://tevent.herokuapp.com/api/v1/user/events
###
GET http://tevent.herokuapp.com/api/v1/user/organizations
