### SIGN IN
POST http://tevent.herokuapp.com/api/v1/signin
Content-type: application/json

{ "name": "Turist", "email": "pol@ya.ruuuu", "secret": "8765" }

> {% client.global.set("auth_token", response.body.token); %}

### LOGIN
POST http://tevent.herokuapp.com/api/v1/login
Content-type: application/json

{ "email": "pol@ya.ruuuu", "secret": "8765" }

> {% client.global.set("auth_token", response.body.token); %}

### AUTH WITH GOOGLE
POST http://tevent.herokuapp.com/api/v1/auth/google
Content-type: application/json

{ "idtoken": "token" }

> {% client.global.set("auth_token", response.body.token); %}

### CHECK TOKEN
GET http://tevent.herokuapp.com/api/v1/auth/validate?token={{auth_token}}







### USER INFO
GET http://tevent.herokuapp.com/api/v1/user
Authorization: Bearer {{auth_token}}
###

PUT http://tevent.herokuapp.com/api/v1/user
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "name": "Pavel", "email": "paul@com" }
###

DELETE http://tevent.herokuapp.com/api/v1/user
Authorization: Bearer {{auth_token}}








### ADD ORGANIZATION
POST http://tevent.herokuapp.com/api/v1/organizations
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "name": "Dev Community", "nick": "devcom", "description": "It's community for developers", "tags": ["dev"] }

### CHANGE
PUT http://tevent.herokuapp.com/api/v1/organizations/1
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "name": "Developers Community", "nick": "devcom", "description": "It's community for developers", "tags": ["dev", "it"] }



### INFO & SEARCH
GET http://tevent.herokuapp.com/api/v1/organizations/1
###
GET http://tevent.herokuapp.com/api/v1/organizations?tags=dev



### SUBSCRIBE TO ORGANIZATION (sub, member, manager, owner)
POST http://tevent.herokuapp.com/api/v1/organizations/1/join
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "participationType": "sub" }

### GET USERS
GET http://tevent.herokuapp.com/api/v1/organizations/1/users
Authorization: Bearer {{auth_token}}

### UNSUBSCRIBE
POST http://tevent.herokuapp.com/api/v1/organizations/1/leave
Authorization: Bearer {{auth_token}}






### CREATE EVENT
POST http://tevent.herokuapp.com/api/v1/events
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "organizationId": 1, "name": "Meetup #1", "description": "It's first meetup for developers",
  "datetime": "2021-01-10T10:15:30+03:00", "location": "Moscow", "capacity": 100, "tags": ["dev", "first"] }



### INFO & SEARCH
GET http://tevent.herokuapp.com/api/v1/events/1
###
GET http://tevent.herokuapp.com/api/v1/events?organization=1
###
GET http://tevent.herokuapp.com/api/v1/events?tags=dev



### REGISTER TO EVENT (online, offline)
POST http://tevent.herokuapp.com/api/v1/events/1/join
Authorization: Bearer {{auth_token}}
Content-type: application/json

{ "participationType": "offline" }

### GET USERS
GET http://tevent.herokuapp.com/api/v1/events/1/users
Authorization: Bearer {{auth_token}}
###
POST http://tevent.herokuapp.com/api/v1/events/1/leave
Authorization: Bearer {{auth_token}}





### USER EVENTS & ORGANIZATIONS
GET http://tevent.herokuapp.com/api/v1/user/events
Authorization: Bearer {{auth_token}}
###
GET http://tevent.herokuapp.com/api/v1/user/organizations
Authorization: Bearer {{auth_token}}
